spring:
  application:
    name: file-converter
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file-converter:
  storage:
    root-directory: storage
  conversion:
    libre-office-command: libreoffice
